Added support for resolving shortcuts in Google Drive
cryptomator/cloud-access-swift pull request #8
Opened 2022-02-10 16:38 UTC by tobihagemann

2022-02-11 10:24 UTC, tobihagemann commented
In its current state, it doesn't work. I'm having trouble with GRDB.

I added a new struct `GoogleDriveShortcut`, which is used in `GoogleDriveItem` as an optional property.

When it tries to save an item to the `GoogleDriveIdentifierCache` that has a non-nil shortcut, it crashes in [GRDB.swift/DatabaseValueConvertible+Encodable.swift#L70](https://github.com/groue/GRDB.swift/blob/v4.14.0/GRDB/Core/Support/StandardLibrary/DatabaseValueConvertible+Encodable.swift#L70).

2022-02-11 13:31 UTC, tobihagemann commented
Solved it. I couldn't figure it out because I read GRDB 5.x documentation. :smile: I think we should upgrade soon! :stuck_out_tongue_winking_eye:

> Since 5.9.0: Types that adopt both `DatabaseValueConvertible` and `Codable` now profit from automatic JSON encoding and decoding.

2022-02-15 09:44 UTC, phil1995 commented
> Solved it. I couldn't figure it out because I read GRDB 5.x documentation. 😄 I think we should upgrade soon! 😜
> 
> > Since 5.9.0: Types that adopt both `DatabaseValueConvertible` and `Codable` now profit from automatic JSON encoding and decoding.

I agree with you that we should upgrade to GRDB 5 very soon. However, I think we can solve it more elegantly already now. Only two things are necessary for this:
1. `GoogleDriveItem` must also conform to the `Codable` protocol instead of just the `Decodable` protocol.    
2. because the change described in 1. makes it no longer mandatory to implement `PersistableRecord` explicitly, we also don't necessarily need the conformance of `GoogleDriveShortcut` to `DatabaseValueConvertible`.

Thus, `GoogleDriveItem` could now look like this:
```swift
struct GoogleDriveItem: Codable, PersistableRecord, FetchableRecord, Equatable {
	static let databaseTableName = "CachedEntries"
	static let cloudPathKey = "cloudPath"
	static let identifierKey = "identifier"
	static let itemTypeKey = "itemType"
	static let shortcutKey = "shortcut"

	let cloudPath: CloudPath
	let identifier: String
	let itemType: CloudItemType
	let shortcut: GoogleDriveShortcut?
}
// Custom Initializer omitted for simplicity
```

For GoogleDriveShortcut the following code is sufficient:
```swift
struct GoogleDriveShortcut: Codable, Equatable {
	let targetIdentifier: String
	let targetItemType: CloudItemType
}
```

2022-02-15 10:05 UTC, phil1995 requested changes

2022-02-15 10:36 UTC, phil1995 approved these changes

2022-02-15 10:38 UTC, merged